### PR TITLE
Revert "Caching, Async & minor changes"

### PR DESCRIPTION
**Pull request by davidwengier**
Reverts davidwengier/SourceGeneratorPlayground#9

@stefanloerwald looks like something in that PR broke how assemblies are referenced, and only the Hello World sample works.

### CODE REVIEW

**Comment by stefanloerwald** [comment]
My sincerest apologies for introducing a breaking change. I believe the reason is the earlier initialization of the metadata references. I'll look into fixing this ASAP and resubmitting a PR.

**Comment by davidwengier** [comment]
It's no problem :)

I thought that too, but even reverting some of the changes didn't help. Honestly I couldn't see any reason why it broke, and the reference system is a complete hack anyway, so it's not too surprising. I can probably just create an allow list of assemblies to reference and it will be fine.

**Comment by stefanloerwald** [comment]
The success of compilation depends on the dlls available in the blazor project, so it certainly is involving something that can be called a hack ;-) I'm in the process of submitting a new PR, which just checks for missing references on every compilation. That fixes it (on my machine).

**Comment by stefanloerwald** [comment]
I've just submitted it as PR #11. I hope you can confirm that everything is back to working as before.

**Pull request merged**
